# CellLock: Bedrock Edition Configuration File

# Prison Cells Configuration
prison_cells:
  cell1:
    x: 100
    y: 64
    z: 200
  cell2:
    x: 150
    y: 64
    z: 250
  # Add more prison cells as needed

# Default cell price
cell_price: 100
